include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unreachable_switch_default: ignore
    unused_element_parameter: ignore
  plugins:
    - custom_lint
  exclude:
    - '**.g.dart'

linter:
  rules:
    # avoid_print: false
    prefer_single_quotes: true
    unnecessary_lambdas: true
    avoid_renaming_method_parameters: false
